version: "3"
services:
  server:
    build: .
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
