version: "3"

services:
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - app-volume:/app/src/server/public
  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app-volume:/var/www/public

volumes:
  app-volume:
